### ISSUE TITLE
Proposal for syntax highlighting improvements

### ISSUE THREAD

**Issue by mkraska** [fiziko/language-cgx#2]
The following criteria prevent wrong command highlighting if such words are parameters or if they are part of other words (like file names or entity names)
+ commands can occure only at the beginning of a line, but can have leading whitespaces. 
+ commands must be followed by a blank or by line end.

The following transformation labels might deserve highlighting if they occure as parameters:
` tra rot rad mir scal`
They can occure in the commands `copy move swep`

**Comment by fiziko** [comment]
Hi Martin,

thanks for pointing this out.

Highlighting was and still is far from being perfect :-). Reason: Until now, I haven't completely understood how to specify the regular expressions properly... Anyway: I made some improvements now, I guess. And submitted my changes. They should be active as soon as you open atom next time... now being on version 0.9.0. Feel free to close issue, if you are happy for now.

![screenshot](https://cloud.githubusercontent.com/assets/5688765/12186744/f0008c2c-b5a5-11e5-8f05-64ec8646b2ed.png)

**Comment by mkraska** [comment]
Thanks for the improvements. I have found these remaining examples of wrong highlighting:

sys mv hcpy* " name i .png"
view elem
sys mv hcpy_2.png SE-zoom.png
read view.fbd
sys mv hcpy_1.png b-mesh.png
read def-plot.fbd

**Comment by fiziko** [comment]
Hi, thanks,

ok, now this is fixed. But other issues remaining unsolved for now, see pic below. I keep these issues
for the experts for now... :-)

![screenshot-2](https://cloud.githubusercontent.com/assets/5688765/12199897/cf991b40-b61b-11e5-81d2-795326d131b1.png)

**Comment by fiziko** [comment]
oh, no, still something else wrong...

**Comment by fiziko** [comment]
Hi Martin,

well, could you check with the new version 0.12.0, please? I could not find any wrong highlighting, but who knows...


![screenshot](https://cloud.githubusercontent.com/assets/5688765/12203446/55150f46-b62f-11e5-9f8b-83589bcb6a76.png)

**Comment by mkraska** [comment]
Still some wrong highlighting.

seta nodes n all
enq nodes fix rec Ra _ _ 1 a
view elem (elem isn't a command here)

My proposal for a search strategy  for commands would be
- must be preceeded by begin of line followed by zero or more whitespace characters 
- and must be followed by at least one whitespace or line end. 
- must match one of the known command strings in a non-case-sensitive way

Something like ^\s+(anim|asgn....)\s|& (probably wrong)

The transformation labels match, whenever they are limited by whitespace.

**Comment by fiziko** [comment]
This makes it easier... please try again with 0.13.0 thanks.

**Comment by fiziko** [comment]
aber jetzt fehlen diese Dinge, die nicht am Anfang der Zeile stehen müssen...

**Comment by fiziko** [comment]
Hi Martin,

I now also capture "tra rot rad mir scal". But it's not as it should be. It's not checked where these words appear...  This will be it for now... :-)

![screenshot](https://cloud.githubusercontent.com/assets/5688765/12207951/f25e0482-b649-11e5-8f8c-3dc0a49ac7cf.png)

**Comment by mkraska** [comment]
Great, thanks a lot!
