### ISSUE TITLE
Indented comments

### ISSUE THREAD

**Issue by mkraska** [fiziko/language-cgx#4]
If comments are indented, e.g. in loops, they aren't recognized as such. In the example below, # mode counter is not recognized. Proposal: Allow for leading whitespace before the comment sign.

 
read solid-modal.frd
# define subset for shaded display
enq all new rec _ _ -100 100 a
comp new do
# set view and properties
rot -z
rot r 30
rot u 30
scal d 2
view elem
# prepare animation 
anim steps 16
valu num 0
valu incr 1
valu end 4
valu pre solid-modal-
valu ext .gif
while num < end
  # mode counter
  valu num + num incr
  valu num int num
  ds num e 4
  plot fv all
  plus f new n
  movi frames auto
  #ds num a 4
  anim start
  valu name & pre num
  valu name & name ext
  sys mv movie.gif name
endwhile

**Comment by fiziko** [comment]
thanks.

Could you please check, if it works now in 1.7.0?

**Comment by mkraska** [comment]
Thanks, works like a charm.
